#!/bin/sh

export GIT_DIR=$1/.git
export GIT_WORK_TREE=$1

REPO_TAG=`git describe --tags --always`
FILE=$1/components/serenity/gen/__Version.cpp.tmp
TARGET=$1/components/serenity/gen/__Version.cpp

mkdir -p $1/components/serenity/gen

echo '// Autogenerated by makefile\n' > $FILE
echo '#include "Define.h"' >> $FILE
echo 'NS_SA_EXT_BEGIN(tools)' >> $FILE
echo "const char * getVersionString() { return \"$REPO_TAG\"; }" >> $FILE
echo "const char * getDocumentsPath() { return \"$1\" \"/docs\"; }" >> $FILE
echo 'NS_SA_EXT_END(tools)' >> $FILE

if cmp -s "$FILE" "$TARGET" ; then
	rm -f $FILE;
else
	rm -f $TARGET;
	mv $FILE $TARGET;
	touch $TARGET;
fi

echo $REPO_TAG
