# Copyright (c) 2017 Roman Katuntsev <sbkarr@stappler.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

DEF_SYSROOT_SIM := "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk"
DEF_SYSROOT_OS := "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk"
XCODE_BIN_PATH := /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

DEF_MIN_IOS_VERSION := 8.0

IOS_EXPORT_PREFIX ?= $(realpath $(GLOBAL_ROOT))

ifdef RELEASE
IOS_ROOT := $(TOOLKIT_OUTPUT)/ios/release
else
IOS_ROOT := $(TOOLKIT_OUTPUT)/ios/debug
endif

ifeq ($(IOS_WRAPPER),1)

.NOTPARALLEL :

endif

ios-libs:
	$(MAKE) -f $(THIS_FILE) IOS_ARCH=armv7 ios-export
	$(MAKE) -f $(THIS_FILE) IOS_ARCH=armv7 IOS_WRAPPER=2 MIN_IOS_VERSION=$(DEF_MIN_IOS_VERSION) SYSROOT=$(DEF_SYSROOT_OS) static
	$(MAKE) -f $(THIS_FILE) IOS_ARCH=armv7s IOS_WRAPPER=2 MIN_IOS_VERSION=$(DEF_MIN_IOS_VERSION) SYSROOT=$(DEF_SYSROOT_OS) static
	$(MAKE) -f $(THIS_FILE) IOS_ARCH=arm64 IOS_WRAPPER=2 MIN_IOS_VERSION=$(DEF_MIN_IOS_VERSION) SYSROOT=$(DEF_SYSROOT_OS) static
	$(MAKE) -f $(THIS_FILE) IOS_ARCH=i386 IOS_WRAPPER=2 MIN_IOS_VERSION=$(DEF_MIN_IOS_VERSION) SYSROOT=$(DEF_SYSROOT_SIM) static
	$(MAKE) -f $(THIS_FILE) IOS_ARCH=x86_64 IOS_WRAPPER=2 MIN_IOS_VERSION=$(DEF_MIN_IOS_VERSION) SYSROOT=$(DEF_SYSROOT_SIM) static

$(IOS_ROOT)/libmaterial.a: $(IOS_ROOT)/armv7/libmaterial.a $(IOS_ROOT)/armv7s/libmaterial.a $(IOS_ROOT)/arm64/libmaterial.a $(IOS_ROOT)/i386/libmaterial.a $(IOS_ROOT)/x86_64/libmaterial.a
	lipo -create -output $(IOS_ROOT)/libmaterial.a $(IOS_ROOT)/armv7/libmaterial.a $(IOS_ROOT)/armv7s/libmaterial.a $(IOS_ROOT)/arm64/libmaterial.a $(IOS_ROOT)/i386/libmaterial.a $(IOS_ROOT)/x86_64/libmaterial.a

$(IOS_ROOT)/libstappler.a: $(IOS_ROOT)/armv7/libstappler.a $(IOS_ROOT)/armv7s/libstappler.a $(IOS_ROOT)/arm64/libstappler.a $(IOS_ROOT)/i386/libstappler.a $(IOS_ROOT)/x86_64/libstappler.a
	lipo -create -output $(IOS_ROOT)/libstappler.a $(IOS_ROOT)/armv7/libstappler.a $(IOS_ROOT)/armv7s/libstappler.a $(IOS_ROOT)/arm64/libstappler.a $(IOS_ROOT)/i386/libstappler.a $(IOS_ROOT)/x86_64/libstappler.a

ios-wrapper: | ios-libs $(IOS_ROOT)/libstappler.a $(IOS_ROOT)/libmaterial.a

ios:
	$(MAKE) -f $(THIS_FILE) IOS_WRAPPER=1 ios-wrapper

ios-clean:
	$(MAKE) -f $(THIS_FILE) IOS_ARCH=armv7 IOS_WRAPPER=2 MIN_IOS_VERSION=$(DEF_MIN_IOS_VERSION) SYSROOT=$(DEF_SYSROOT_OS) clean
	$(MAKE) -f $(THIS_FILE) IOS_ARCH=armv7s IOS_WRAPPER=2 MIN_IOS_VERSION=$(DEF_MIN_IOS_VERSION) SYSROOT=$(DEF_SYSROOT_OS) clean
	$(MAKE) -f $(THIS_FILE) IOS_ARCH=arm64 IOS_WRAPPER=2 MIN_IOS_VERSION=$(DEF_MIN_IOS_VERSION) SYSROOT=$(DEF_SYSROOT_OS) clean
	$(MAKE) -f $(THIS_FILE) IOS_ARCH=i386 IOS_WRAPPER=2 MIN_IOS_VERSION=$(DEF_MIN_IOS_VERSION) SYSROOT=$(DEF_SYSROOT_SIM) clean
	$(MAKE) -f $(THIS_FILE) IOS_ARCH=x86_64 IOS_WRAPPER=2 MIN_IOS_VERSION=$(DEF_MIN_IOS_VERSION) SYSROOT=$(DEF_SYSROOT_SIM) clean

ios-export:
	$(GLOBAL_MKDIR) $(GLOBAL_ROOT)/build/ios
	@echo '// Autogenerated by makefile' > $(GLOBAL_ROOT)/build/ios/export.xcconfig
	@echo '\nSTAPPLER_INCLUDES = $(patsubst $(GLOBAL_ROOT)/%,$(IOS_EXPORT_PREFIX)/%,$(filter-out $(addprefix $(GLOBAL_ROOT)/,$(OSTYPE_INCLUDE) $(OSTYPE_INCLUDE)/cairo),$(STAPPLER_INCLUDES)))' >> $(GLOBAL_ROOT)/build/ios/export.xcconfig
	@echo '\nMATERIAL_INCLUDES = $(patsubst $(GLOBAL_ROOT)/%,$(IOS_EXPORT_PREFIX)/%,$(filter-out $(addprefix $(GLOBAL_ROOT)/,$(OSTYPE_INCLUDE) $(OSTYPE_INCLUDE)/cairo),$(MATERIAL_INCLUDES)))' >> $(GLOBAL_ROOT)/build/ios/export.xcconfig

.PHONY: ios ios-wrapper ios-clean ios-libs ios-export
