STAPPLER_ROOT = ../..

LOCAL_OUTDIR := bin
LOCAL_EXECUTABLE := doc

LOCAL_TOOLKIT := common

LOCAL_ROOT = .

LOCAL_SRCS_DIRS := src
LOCAL_SRCS_OBJS :=

LOCAL_INCLUDES_DIRS := src
LOCAL_INCLUDES_OBJS :=

LOCAL_MAIN := main.cpp

LOCAL_LIBS =

#.local_prebuild:
#	@echo test

include $(STAPPLER_ROOT)/make/universal.mk
